
package views;

import javax.swing.JOptionPane;
import models.Client;
import controllers.ClientController;

public class ClientRegisterForm extends javax.swing.JFrame {
    
    Client cliente = new Client();
    
    public ClientRegisterForm() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public ClientRegisterForm(String identificacion) {
        initComponents();
        setLocationRelativeTo(null);
        this.cliente = ClientController.findCliente(identificacion);
        this.loadData();
    }
    
    public void loadData() {
        txtnomcompleto.setText(this.cliente.getNomuser());
        txtcelular.setText(this.cliente.getCelular());
        txtID.setText(this.cliente.getIdentificacion());
        txtID.setEditable(false);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnomcompleto = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtcelular = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        combotipoID = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Tipo de Docuemento");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 160, 20));

        jLabel2.setText("No. Identifiación");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel4.setText("Nombre Completo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        jLabel5.setText("Celular");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, 20));

        txtnomcompleto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnomcompletoKeyTyped(evt);
            }
        });
        jPanel1.add(txtnomcompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 390, 40));

        txtID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtIDMouseEntered(evt);
            }
        });
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIDKeyTyped(evt);
            }
        });
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 390, 40));

        txtcelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcelularKeyTyped(evt);
            }
        });
        jPanel1.add(txtcelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 390, 40));

        jButton1.setBackground(new java.awt.Color(190, 0, 43));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 210, 50));

        combotipoID.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cedula de Ciudadanía", "Cedula de Extranjería", " Pasaporte" }));
        combotipoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combotipoIDActionPerformed(evt);
            }
        });
        jPanel1.add(combotipoID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 240, 40));

        jLabel6.setBackground(new java.awt.Color(190, 0, 43));
        jLabel6.setForeground(new java.awt.Color(190, 0, 43));
        jLabel6.setText("REGISTRO DE CLIENTE");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jButton3.setBackground(new java.awt.Color(190, 0, 43));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Regresar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 100, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow-back-1-icon.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
        ClientGestion cg = new ClientGestion();
        cg.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    
   /* public static boolean  validFormNum(String datos){
        return datos.matches("[0-9]{1,10}");
    }
    
    public static boolean  validFormLetr(String datos){
        return datos.matches("[a-zA-Z]{1,50}");
    }
    
    */
    
    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int valid = 0;
        if(!txtnomcompleto.getText().isEmpty()){
            valid++;
        }if(!txtcelular.getText().isEmpty()){
           valid++;
        }if(!combotipoID.getSelectedItem().toString().isEmpty()){
           valid++;
        }if(valid == 3){
            
            if (this.cliente.getIdentificacion() != null) {
                
                this.cliente.setNomuser(txtnomcompleto.getText());
                this.cliente.setCelular(txtcelular.getText());
                this.cliente.setTipoId(combotipoID.getSelectedItem().toString());
                if(ClientController.updateClient(this.cliente) != null) {
                    JOptionPane.showMessageDialog(this, "Edicion Exitosa \n\n Nombre : "
                    +txtnomcompleto.getText());
                    dispose();   
                    ClientGestion clg = new ClientGestion();
                    clg.setVisible(true); 
                } else {
                    JOptionPane.showMessageDialog(this, "El cliente no se pudo editar");
                }

            } else {
                
                Client clte = new Client(
                    txtnomcompleto.getText(),
                    txtcelular.getText(),
                    txtID.getText(),
                    combotipoID.getSelectedItem().toString()
                );

                ClientController.aggNewClient(clte);

                JOptionPane.showMessageDialog(this, "Registro Exitoso \n\n Nombre : "
                +txtnomcompleto.getText());
                dispose();   
                ClientGestion clg = new ClientGestion();
                clg.setVisible(true);       
            }

        }else{
            JOptionPane.showMessageDialog(this, "!Datos Incompletos");
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void combotipoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combotipoIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combotipoIDActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtIDActionPerformed

    private void txtIDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIDMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDMouseEntered

    private void txtIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyTyped
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_txtIDKeyTyped

    private void txtnomcompletoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomcompletoKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtnomcompletoKeyTyped

    private void txtcelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcelularKeyTyped
        // TODO add your handling code here:
   
    }//GEN-LAST:event_txtcelularKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientRegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientRegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientRegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientRegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientRegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox combotipoID;
    public javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtcelular;
    private javax.swing.JTextField txtnomcompleto;
    // End of variables declaration//GEN-END:variables
}
