/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.ClientController;
import controllers.ProjectController;
import javax.swing.JOptionPane;
import models.Project;

/**
 *
 * @author jair
 */
public class ProjectRegisterForm extends javax.swing.JFrame {

    Project proyecto = new Project();
    
    public ProjectRegisterForm() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public ProjectRegisterForm(String nombreProyecto) {
        initComponents();
        setLocationRelativeTo(null);
        this.proyecto = ProjectController.findProyect(nombreProyecto);
        this.loadDataForm();
    }
    
    public void loadDataForm(){
        txtnomproyecto.setText(this.proyecto.getNomProyecto());
        txtdescripcion.setText(this.proyecto.getDescripcion());
        txtactividades.setText(this.proyecto.getActividades());
        txtpresupuesto.setText(this.proyecto.getPresuPuesto());
        txtfechinicio.setText(this.proyecto.getFechInicio());
        txtfechfinal.setText(this.proyecto.getFechFinal());
        txtnomproyecto.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtactividades = new javax.swing.JTextField();
        txtdescripcion = new javax.swing.JTextField();
        txtpresupuesto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtfechinicio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtnomproyecto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtfechfinal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Descripción");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel5.setText("Actividades");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, 20));
        jPanel1.add(txtactividades, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 390, 40));
        jPanel1.add(txtdescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 390, 40));
        jPanel1.add(txtpresupuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 390, 40));

        jButton1.setBackground(new java.awt.Color(190, 0, 43));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 410, 50));

        jLabel6.setBackground(new java.awt.Color(190, 0, 43));
        jLabel6.setForeground(new java.awt.Color(190, 0, 43));
        jLabel6.setText("REGISTRO DE PROYECTO");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        jButton3.setBackground(new java.awt.Color(190, 0, 43));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Regresar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 100, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow-back-1-icon.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel8.setText("Presupuesto");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, 20));
        jPanel1.add(txtfechinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 390, 40));

        jLabel9.setText("Fecha de Inicio");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, -1, 20));
        jPanel1.add(txtnomproyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 390, 40));

        jLabel10.setText("Nombre Proyecto");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));
        jPanel1.add(txtfechfinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 390, 40));

        jLabel11.setText("Fecha de Cierre");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 998, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
        ProjectGestion pgt = new ProjectGestion();
        pgt.setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
            if(this.proyecto.getNomProyecto() == null) {
            
                this.proyecto = new Project(
                    txtnomproyecto.getText(),
                    txtdescripcion.getText(),
                    txtactividades.getText(),
                    txtpresupuesto.getText(),
                    txtfechinicio.getText(),
                    txtfechfinal.getText(),
                    ClientController.getListClient().get(1)
                    );
                
                ProjectController.aggNewProject(this.proyecto);
                dispose();
                ProjectGestion pgt = new ProjectGestion();
                pgt.setVisible(true);

            }else {

                this.proyecto.setDescripcion(txtdescripcion.getText());
                this.proyecto.setActividades(txtactividades.getText());
                this.proyecto.setPresuPuesto(txtpresupuesto.getText());
                this.proyecto.setFechInicio(txtfechinicio.getText());
                this.proyecto.setFechFinal(txtfechfinal.getText());
                ProjectController.updateProject(this.proyecto);
                dispose();
                ProjectGestion pgt = new ProjectGestion();
                pgt.setVisible(true);
                
            }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectRegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectRegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectRegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectRegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjectRegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtactividades;
    private javax.swing.JTextField txtdescripcion;
    private javax.swing.JTextField txtfechfinal;
    private javax.swing.JTextField txtfechinicio;
    private javax.swing.JTextField txtnomproyecto;
    private javax.swing.JTextField txtpresupuesto;
    // End of variables declaration//GEN-END:variables
}
